services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_PROJECT_ID: ${REACT_APP_PROJECT_ID}
        REACT_APP_BACK_API: ${REACT_APP_BACK_API}
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
      - REACT_APP_BACK_API=${REACT_APP_BACK_API}
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./back-end/uploads:/app/uploads
