services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "36374:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "3015:3000"
    environment:
      - DB_HOST="URL de la base de données"
      - DB_USER="Nom d'utilisateur de la base de données"
      - DB_PASSWORD="Mot de passe de la base de données"
      - DB_NAME="Nom de la base de données"
      - GROQ_API_KEY="API de Grok pour les fonctionalités d'intelligence artificielle"
    volumes:
      - ./back-end/uploads:/app/uploads
