# Étape 1 : Utiliser une image de base Node.js
FROM node:16

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers de dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le code source
COPY . .

# Étape 6 : Exposer le port sur lequel votre serveur Express.js écoute
EXPOSE 3000 

# Étape 7 : Démarrer Nginx
CMD ["node", "serveur.js"]