# Étape 1: Utiliser une image de base officielle de Node.js
FROM node:18-alpine

# Étape 2: Définir le répertoire de travail
WORKDIR /app

# Étape 3: Copier les fichiers package.json et package-lock.json pour optimiser le cache de Docker
COPY package*.json ./

# Étape 4: Installer les dépendances du projet
RUN npm install --production

# Étape 5: Copier tous les fichiers du projet dans le conteneur
COPY . .

# Étape 6: Exposer le port sur lequel l'application va tourner
EXPOSE 3000

# Étape 8: Lancer le serveur Node.js
CMD ["node", "serveur.js"]
